//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDEK {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CDEK.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дирхам ОАЭ.
        /// </summary>
        public static string AED {
            get {
                return ResourceManager.GetString("AED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Армянский драм.
        /// </summary>
        public static string AMD {
            get {
                return ResourceManager.GetString("AMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Указанная вами версия API не поддерживается.
        /// </summary>
        public static string APIError {
            get {
                return ResourceManager.GetString("APIError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка авторизации.
        /// </summary>
        public static string AuthorisationError {
            get {
                return ResourceManager.GetString("AuthorisationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Белорусский рубль.
        /// </summary>
        public static string BYN {
            get {
                return ResourceManager.GetString("BYN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Китайский экспресс.
        /// </summary>
        public static string ChineseExpress {
            get {
                return ResourceManager.GetString("ChineseExpress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Услуга по доставке из Китая в Россию, Белоруссию и Казахстан. Стоимость разбита по интервалам:
        ///- до 200 гр;
        ///- каждые последующие 100 гр до 1 кг;
        ///- каждый последующий 1кг свыше 1 кг..
        /// </summary>
        public static string ChineseExpressDescription {
            get {
                return ResourceManager.GetString("ChineseExpressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Китайский экспресс дверь-дверь (Д-Д).
        /// </summary>
        public static string ChineseExpressDoorDoor {
            get {
                return ResourceManager.GetString("ChineseExpressDoorDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Китайский экспресс дверь-склад (Д-С).
        /// </summary>
        public static string ChineseExpressDoorWarehouse {
            get {
                return ResourceManager.GetString("ChineseExpressDoorWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Китайский экспресс склад-дверь (С-Д).
        /// </summary>
        public static string ChineseExpressWarehouseDoor {
            get {
                return ResourceManager.GetString("ChineseExpressWarehouseDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Китайский экспресс склад-склад (С-С).
        /// </summary>
        public static string ChineseExpressWarehouseWarehouse {
            get {
                return ResourceManager.GetString("ChineseExpressWarehouseWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Юань.
        /// </summary>
        public static string CNY {
            get {
                return ResourceManager.GetString("CNY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка декодирования данных. Ожидается &lt;json или jsop&gt;.
        /// </summary>
        public static string DataDecodingError {
            get {
                return ResourceManager.GetString("DataDecodingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неправильно задан формат данных.
        /// </summary>
        public static string DataFormatSetIncorrectly {
            get {
                return ResourceManager.GetString("DataFormatSetIncorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка задания режима доставки.
        /// </summary>
        public static string DeliveryModeSettingError {
            get {
                return ResourceManager.GetString("DeliveryModeSettingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не задан город-получатель.
        /// </summary>
        public static string DestinationCityNot {
            get {
                return ResourceManager.GetString("DestinationCityNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на дверь-дверь.
        /// </summary>
        public static string DoorDoor {
            get {
                return ResourceManager.GetString("DoorDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Курьер забирает груз у отправителя и доставляет получателю на указанный адрес..
        /// </summary>
        public static string DoorDoorDescription {
            get {
                return ResourceManager.GetString("DoorDoorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на дверь-постамат.
        /// </summary>
        public static string DoorPostamat {
            get {
                return ResourceManager.GetString("DoorPostamat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Курьер забирает груз у отправителя и доставляет в указанный постамат, получатель забирает груз самостоятельно из постамата.
        /// </summary>
        public static string DoorPostamatDecription {
            get {
                return ResourceManager.GetString("DoorPostamatDecription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на дверь-склад.
        /// </summary>
        public static string DoorWarehouse {
            get {
                return ResourceManager.GetString("DoorWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Курьер забирает груз у отправителя и довозит до склада, получатель забирает груз самостоятельно в ПВЗ (самозабор)..
        /// </summary>
        public static string DoorWarehouseDescription {
            get {
                return ResourceManager.GetString("DoorWarehouseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недорогая доставка грузов внутри РФ, Белоруссии, Казахстана, Армении, Киргизии и между этим странами, ЖД и автотранспортом (доставка грузов с увеличением сроков)..
        /// </summary>
        public static string EconomyExpressDescription {
            get {
                return ResourceManager.GetString("EconomyExpressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экономичный экспресс дверь-дверь.
        /// </summary>
        public static string EconomyExpressDoorDoor {
            get {
                return ResourceManager.GetString("EconomyExpressDoorDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экономичный экспресс дверь-склад.
        /// </summary>
        public static string EconomyExpressDoorWarehouse {
            get {
                return ResourceManager.GetString("EconomyExpressDoorWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экономичный экспресс склад-дверь.
        /// </summary>
        public static string EconomyExpressWarehouseDoor {
            get {
                return ResourceManager.GetString("EconomyExpressWarehouseDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экономичная доставка.
        /// </summary>
        public static string EconomyShipping {
            get {
                return ResourceManager.GetString("EconomyShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недорогая доставка грузов по России ЖД и автотранспортом (доставка грузов с увеличением сроков)..
        /// </summary>
        public static string EconomyShippingDescription {
            get {
                return ResourceManager.GetString("EconomyShippingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экономичный экспресс склад-склад.
        /// </summary>
        public static string EconomyShippingWarehouseWarehouse {
            get {
                return ResourceManager.GetString("EconomyShippingWarehouseWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при указании параметров места.
        /// </summary>
        public static string ErrorWhileSpecifyingLocationParameters {
            get {
                return ResourceManager.GetString("ErrorWhileSpecifyingLocationParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Евро.
        /// </summary>
        public static string EUR {
            get {
                return ResourceManager.GetString("EUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспресс.
        /// </summary>
        public static string Express {
            get {
                return ResourceManager.GetString("Express", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Классическая экспресс-доставка по России документов и грузов до 30 кг..
        /// </summary>
        public static string ExpressLightDescription {
            get {
                return ResourceManager.GetString("ExpressLightDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспресс лайт дверь-дверь.
        /// </summary>
        public static string ExpressLightDoorDoor {
            get {
                return ResourceManager.GetString("ExpressLightDoorDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспресс лайт дверь-постамат.
        /// </summary>
        public static string ExpressLightDoorPostamat {
            get {
                return ResourceManager.GetString("ExpressLightDoorPostamat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Классическая экспресс-доставка документов и грузов внутри РФ, Белоруссии, Казахстана, Армении, Киргизии и между этим странами..
        /// </summary>
        public static string ExpressLightInternationalDescription {
            get {
                return ResourceManager.GetString("ExpressLightInternationalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспресс лайт дверь-склад(2).
        /// </summary>
        public static string ExpressLightInternationalDoorWarehouse {
            get {
                return ResourceManager.GetString("ExpressLightInternationalDoorWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспресс лайт склад-дверь(2).
        /// </summary>
        public static string ExpressLightInternationalWarehouseDoor {
            get {
                return ResourceManager.GetString("ExpressLightInternationalWarehouseDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспресс лайт склад-склад(2).
        /// </summary>
        public static string ExpressLightInternationalWarehouseWarehouse {
            get {
                return ResourceManager.GetString("ExpressLightInternationalWarehouseWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на До 30 кг.
        /// </summary>
        public static string ExpressLightLimit {
            get {
                return ResourceManager.GetString("ExpressLightLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспресс лайт склад-постамат.
        /// </summary>
        public static string ExpressLightWarehousePostamat {
            get {
                return ResourceManager.GetString("ExpressLightWarehousePostamat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Классическая экспресс-доставка внутри РФ, Белоруссии, Казахстана, Армении, Киргизии и между этим странами..
        /// </summary>
        public static string ExpressSheavyweightsDescription {
            get {
                return ResourceManager.GetString("ExpressSheavyweightsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспресс тяжеловесы дверь-дверь.
        /// </summary>
        public static string ExpressSheavyweightsDoorDoor {
            get {
                return ResourceManager.GetString("ExpressSheavyweightsDoorDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспресс тяжеловесы дверь-склад.
        /// </summary>
        public static string ExpressSheavyweightsDoorWarehouse {
            get {
                return ResourceManager.GetString("ExpressSheavyweightsDoorWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспресс тяжеловесы склад-дверь.
        /// </summary>
        public static string ExpressSheavyweightsWarehouseDoor {
            get {
                return ResourceManager.GetString("ExpressSheavyweightsWarehouseDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспресс тяжеловесы склад-склад.
        /// </summary>
        public static string ExpressSheavyweightsWarehouseWarehouse {
            get {
                return ResourceManager.GetString("ExpressSheavyweightsWarehouseWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Срочная доставка.
        /// </summary>
        public static string ExpressВelivery {
            get {
                return ResourceManager.GetString("ExpressВelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Срочная доставка документов и грузов «из рук в руки» по России к определенному часу..
        /// </summary>
        public static string ExpressВeliveryDescription {
            get {
                return ResourceManager.GetString("ExpressВeliveryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Супер-экспресс до 18.
        /// </summary>
        public static string ExpressВeliveryTo18 {
            get {
                return ResourceManager.GetString("ExpressВeliveryTo18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фунт стерлингов.
        /// </summary>
        public static string GBP {
            get {
                return ResourceManager.GetString("GBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бросил трубку.
        /// </summary>
        public static string IHungUp {
            get {
                return ResourceManager.GetString("IHungUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внутренняя ошибка на сервере. Обратитесь к программистам компании СДЭК для исправления..
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно однозначно идентифицировать город-отправитель по почтовому индексу.
        /// </summary>
        public static string ItIsImpossiblePostalCodeError {
            get {
                return ResourceManager.GetString("ItIsImpossiblePostalCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно осуществить доставку по этому направлению при заданных условиях.
        /// </summary>
        public static string ItIsImpossibleToCarryOutDelivery {
            get {
                return ResourceManager.GetString("ItIsImpossibleToCarryOutDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно однозначно идентифицировать город-получатель по почтовому индексу.
        /// </summary>
        public static string ItIsImpossibleToUniquelyIdentifyTheReceivingCity {
            get {
                return ResourceManager.GetString("ItIsImpossibleToUniquelyIdentifyTheReceivingCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Киргизский сом.
        /// </summary>
        public static string KGS {
            get {
                return ResourceManager.GetString("KGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Южнокорейская вона.
        /// </summary>
        public static string KRW {
            get {
                return ResourceManager.GetString("KRW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тенге.
        /// </summary>
        public static string KZT {
            get {
                return ResourceManager.GetString("KZT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Быстрая экономичная доставка грузов по России.
        /// </summary>
        public static string MainExpressDescription {
            get {
                return ResourceManager.GetString("MainExpressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Быстрая экономичная доставка грузов по России.
        /// </summary>
        public static string MainExpressDescription1 {
            get {
                return ResourceManager.GetString("MainExpressDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Магистральный экспресс дверь-дверь.
        /// </summary>
        public static string MainExpressDoorDoor {
            get {
                return ResourceManager.GetString("MainExpressDoorDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Магистральный экспресс дверь-склад.
        /// </summary>
        public static string MainExpressDoorWarehouse {
            get {
                return ResourceManager.GetString("MainExpressDoorWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Магистральный экспресс склад-дверь.
        /// </summary>
        public static string MainExpressWarehouseDoor {
            get {
                return ResourceManager.GetString("MainExpressWarehouseDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Магистральный экспресс Магистральный экспресс склад-склад.
        /// </summary>
        public static string MainExpressWarehouseWarehouse {
            get {
                return ResourceManager.GetString("MainExpressWarehouseWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Быстрая экономичная доставка грузов к определенному часу.
        /// </summary>
        public static string MainSuperExpressDescription {
            get {
                return ResourceManager.GetString("MainSuperExpressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Быстрая экономичная доставка грузов к определенному часу.
        /// </summary>
        public static string MainSuperExpressDescription1 {
            get {
                return ResourceManager.GetString("MainSuperExpressDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Магистральный супер-экспресс дверь-дверь.
        /// </summary>
        public static string MainSuperExpressDoorDoor {
            get {
                return ResourceManager.GetString("MainSuperExpressDoorDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Магистральный супер-экспресс дверь-склад.
        /// </summary>
        public static string MainSuperExpressDoorWarehouse {
            get {
                return ResourceManager.GetString("MainSuperExpressDoorWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Магистральный супер-экспресс склад-дверь.
        /// </summary>
        public static string MainSuperExpressWarehouseDoor {
            get {
                return ResourceManager.GetString("MainSuperExpressWarehouseDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Магистральный супер-экспресс склад-склад.
        /// </summary>
        public static string MainSuperExpressWarehouseWarehouse {
            get {
                return ResourceManager.GetString("MainSuperExpressWarehouseWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Монгольский тугрик.
        /// </summary>
        public static string MNT {
            get {
                return ResourceManager.GetString("MNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не задано ни одного места для отправления.
        /// </summary>
        public static string NoDepartureLocation {
            get {
                return ResourceManager.GetString("NoDepartureLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон занят.
        /// </summary>
        public static string PhoneIsBusy {
            get {
                return ResourceManager.GetString("PhoneIsBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон не указан.
        /// </summary>
        public static string PhoneNotSpecified {
            get {
                return ResourceManager.GetString("PhoneNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сброс.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Российский рубль.
        /// </summary>
        public static string RUB {
            get {
                return ResourceManager.GetString("RUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не задан город-отправитель.
        /// </summary>
        public static string SenderCityNot {
            get {
                return ResourceManager.GetString("SenderCityNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тишина.
        /// </summary>
        public static string Silence {
            get {
                return ResourceManager.GetString("Silence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон неверный.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отказ в получении.
        /// </summary>
        public static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на УПАКОВКА 1.
        /// </summary>
        public static string String100 {
            get {
                return ResourceManager.GetString("String100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на УПАКОВКА 2.
        /// </summary>
        public static string String101 {
            get {
                return ResourceManager.GetString("String101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на АРЕНДА КУРЬЕРА.
        /// </summary>
        public static string String102 {
            get {
                return ResourceManager.GetString("String102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СМС УВЕДОМЛЕНИЕ.
        /// </summary>
        public static string String103 {
            get {
                return ResourceManager.GetString("String103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПРИМЕРКА НА ДОМУ.
        /// </summary>
        public static string String104 {
            get {
                return ResourceManager.GetString("String104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СКАН ДОКУМЕНТОВ.
        /// </summary>
        public static string String105 {
            get {
                return ResourceManager.GetString("String105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПОДЪЕМ НА ЭТАЖ РУЧНОЙ.
        /// </summary>
        public static string String106 {
            get {
                return ResourceManager.GetString("String106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПОДЪЕМ НА ЭТАЖ ЛИФТОМ.
        /// </summary>
        public static string String107 {
            get {
                return ResourceManager.GetString("String107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПРОЗВОН.
        /// </summary>
        public static string String108 {
            get {
                return ResourceManager.GetString("String108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЧАСТИЧНАЯ ДОСТАВКА.
        /// </summary>
        public static string String109 {
            get {
                return ResourceManager.GetString("String109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отказ от оплаты.
        /// </summary>
        public static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОСМОТР ВЛОЖЕНИЯ.
        /// </summary>
        public static string String110 {
            get {
                return ResourceManager.GetString("String110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ТЕПЛОВОЙ РЕЖИМ.
        /// </summary>
        public static string String111 {
            get {
                return ResourceManager.GetString("String111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВОЗВРАТ ДОКУМЕНТОВ.
        /// </summary>
        public static string String112 {
            get {
                return ResourceManager.GetString("String112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на АГЕНТСКОЕ ВОЗНАГРАЖДЕНИЕ.
        /// </summary>
        public static string String113 {
            get {
                return ResourceManager.GetString("String113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на РЕВЕРС.
        /// </summary>
        public static string String114 {
            get {
                return ResourceManager.GetString("String114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обеспечение страховой защиты посылки. Размер дополнительного сбора страхования вычисляется от размера объявленной стоимости отправления. (Услуга начисляется автоматически для всех заказов типа &quot;интернет-магазин&quot;, не разрешена для самостоятельной передачи в тэге AddService.).
        /// </summary>
        public static string String115 {
            get {
                return ResourceManager.GetString("String115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Компания СДЭК осуществляет доставку и отправление документов и грузов в выходные и нерабочие дни.
        ///
        ///При доставке или отправлении документов или грузов в выходной день к базовому тарифу добавляется 300 руб..
        /// </summary>
        public static string String116 {
            get {
                return ResourceManager.GetString("String116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При отправке тяжелых грузов,
        ///
        ///если вес 1 места составляет от 75 до 200 кг, то тариф увеличивается на 18 руб за каждый килограмм,
        ///
        ///если вес 1 места более 200 кг, то тариф увеличивается на 25 руб. за каждый килограмм.
        ///
        ///Также возможен индивидуальный расчет стоимости доставки тяжелых грузов.
        ///
        ///Тарифы на такие отправления будут рассчитаны индивидуально и в короткие сроки (не более 1 рабочего дня) и могут быть значительно дешевле наших базовых тарифов..
        /// </summary>
        public static string String117 {
            get {
                return ResourceManager.GetString("String117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При доставке негабаритного отправления, размер одной из сторон которого превышает 1,5 м, тариф увеличивается на 60 % (если отправление рассчитывается не по объемному весу).
        ///При доставке негабаритного отправления, размер одной из сторон которого превышает 2,2 м, тариф увеличивается на 100 % (если отправление рассчитывается не по объемному весу)..
        /// </summary>
        public static string String118 {
            get {
                return ResourceManager.GetString("String118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кроме обычных документов и грузов, компания СДЭК готова доставить отправления, содержащие опасные грузы (кроме запрещенных к перевозке).
        ///
        ///В связи с определенным риском стоимость доставки грузов, относящихся к категории опасных, увеличивается в 1,5 раза..
        /// </summary>
        public static string String119 {
            get {
                return ResourceManager.GetString("String119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контактное лицо в компании не работает.
        /// </summary>
        public static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на К приезду курьера Отправление должно быть подготовлено.
        ///
        ///По правилам компании СДЭК курьер может ожидать передачи или получения отправления не более 15 минут.
        ///
        ///В случаях, когда курьер дожидается приема или передачи Отправления более 15 минут, взимается дополнительный сбор в размере 170 рублей.
        ///
        ///Не допускается на тарифах Посылка..
        /// </summary>
        public static string String120 {
            get {
                return ResourceManager.GetString("String120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При необходимости наша компания предоставляет возможность хранения груза на складе, первые 7 дней — БЕСПЛАТНО.
        ///
        ///Начиная с восьмых суток, плата за хранение осуществляется по следующим тарифам:
        ///
        ///стандартного отправления (1 место размером до 25*40*60см) - основной тариф 15 руб./место за 1 календарный день, включая выходные и праздничные дни;
        ///
        ///не стандартного отправления (1 место размером более 25*40*60см) - основной тариф 30 руб./место за 1 календарный день, включая выходные и праздничные дни..
        /// </summary>
        public static string String121 {
            get {
                return ResourceManager.GetString("String121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнительный сбор от кредитного контроля СДЭК..
        /// </summary>
        public static string String122 {
            get {
                return ResourceManager.GetString("String122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В случаях, когда забор или доставка груза курьером осуществляется из удаленного района города, взимается дополнительная плата.
        ///
        ///Установленный перечень удаленных районов Вы можете узнать по телефону единой справочной службы 8-800-250-04-05 (звонок бесплатный) или у менеджеров компании в офисе Вашего города..
        /// </summary>
        public static string String123 {
            get {
                return ResourceManager.GetString("String123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Когда требуется повторный вызов курьера по ранее аннулированному заказу либо доставка/забор не были осуществлены по вине клиента, начисляется дополнительный сбор.
        ///
        ///Размер сбора зависит от веса отправления и стоимости доставки по городу..
        /// </summary>
        public static string String124 {
            get {
                return ResourceManager.GetString("String124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнительная услуга забора груза в городе отправителя, при условии, что тариф доставки с режимом «от склада» (не доступна для тарифов Посылка).
        /// </summary>
        public static string String125 {
            get {
                return ResourceManager.GetString("String125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнительная услуга доставки груза в городе получателя, при условии, что тариф доставки с режимом «до склада» (только для тарифов «Магистральный», «Магистральный супер-экспресс»).
        /// </summary>
        public static string String126 {
            get {
                return ResourceManager.GetString("String126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнительный сбор от кредитного контроля СДЭК..
        /// </summary>
        public static string String127 {
            get {
                return ResourceManager.GetString("String127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для большей сохранности Вашего Отправления компания СДЭК предлагает услуги по обрешетке груза. Стоимость обрешетки для каждого Отправления рассчитывается индивидуально. Т.е. это индивидуальная упаковка груза..
        /// </summary>
        public static string String128 {
            get {
                return ResourceManager.GetString("String128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стоимость коробки размером 310*215*280мм — 30 руб. (для грузов до 10 кг)..
        /// </summary>
        public static string String129 {
            get {
                return ResourceManager.GetString("String129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контактное лицо отсутствует.
        /// </summary>
        public static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стоимость коробки размером 430*310*280мм — 45 руб. (для грузов до 15 кг)..
        /// </summary>
        public static string String130 {
            get {
                return ResourceManager.GetString("String130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Когда необходимо доставить или принять документы в Федеральные службы, такие как: налоговые органы, министерства, посольства, суды, службы надзора и т.д., а также по заказам, требующим ожидания более часа, наша компания готова предоставить курьера.
        ///Стоимость услуги 170 руб./ час, минимальная оплата за 3 часа (510 руб)..
        /// </summary>
        public static string String131 {
            get {
                return ResourceManager.GetString("String131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Компания СДЭК предлагает каждому клиенту оформить услугу &quot;смс-уведомление о доставке&quot;.
        ///
        ///Отправителю высылается сообщение с датой и временем доставки. Стоимость услуги 5 рублей..
        /// </summary>
        public static string String132 {
            get {
                return ResourceManager.GetString("String132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Курьер доставляет покупателю несколько единиц товара (одежда, обувь и пр.) для примерки..
        /// </summary>
        public static string String133 {
            get {
                return ResourceManager.GetString("String133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для подтверждения факта доставки мы можем предоставить Вам скан документов с подписью получателя. Стоимость услуги 50 руб..
        /// </summary>
        public static string String134 {
            get {
                return ResourceManager.GetString("String134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Услуга предоставляется при необходимости подъема на этаж крупногабаритных и тяжелых отправлений (весом от 10 кг).
        ///Разделяется на 2 вида: «Подъем на этаж ручной» и «Подъем на этаж лифтом».
        ///Стоимость услуги «Подъем на этаж ручной» (без лифта)для веса до 30 кг включительно — 50 руб. каждый этаж
        ///
        ///для веса 31-50 кг — 70 руб. каждый этаж
        ///
        ///для веса 51-100 кг — 100 руб. каждый этаж
        ///
        ///для веса 101-150 кг — 130 руб. каждый этаж
        ///
        ///для веса свыше 150 кг — 150 руб. каждый этаж
        ///
        ///Стоимость услуги «Подъем на этаж [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string String135 {
            get {
                return ResourceManager.GetString("String135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Услуга для ИМ &quot;Прозвон&quot; включает в себя предварительный прозвон получателей перед доставкой операторами call-центра. Стоимость услуги 15 руб. 1 заказ..
        /// </summary>
        public static string String136 {
            get {
                return ResourceManager.GetString("String136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Во время доставки товара покупатель может отказаться от одной или нескольких позиций, и выкупить только часть заказа (Если в заказе указано одно вложение, услуга не подключается.).
        /// </summary>
        public static string String137 {
            get {
                return ResourceManager.GetString("String137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Направления, по которым возможна доставка с тепловым режимом: Кемерово-Новокузнецк, Новосибирск-Красноярск, Новосибирск-Кемерово, Новосибирск-Томск, Новосибирск-Омск, Новосибирск-Барнаул, Барнаул-Горно-Алтайск И В ОБРАТНЫХ НАПРАВЛЕНИЯХ!.
        /// </summary>
        public static string String138 {
            get {
                return ResourceManager.GetString("String138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Служба доставки «СДЭК» предоставляет услугу обратной доставки сопроводительных документов с отметками получателя, а также возврат товаров для ИМ и других торговых предприятий..
        /// </summary>
        public static string String139 {
            get {
                return ResourceManager.GetString("String139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Груз отправили через другую компанию.
        /// </summary>
        public static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наша компания оказывает услуги по приему  денежных средств от клиента за товар и РКО.
        /// </summary>
        public static string String140 {
            get {
                return ResourceManager.GetString("String140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обратный заказ на доставку от получателя до отправителя. Например, подписанные документы..
        /// </summary>
        public static string String141 {
            get {
                return ResourceManager.GetString("String141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверка покупателем содержимого заказа до его оплаты (вскрытие посылки)..
        /// </summary>
        public static string String142 {
            get {
                return ResourceManager.GetString("String142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не дозвонился.
        /// </summary>
        public static string String15 {
            get {
                return ResourceManager.GetString("String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Частичная доставка.
        /// </summary>
        public static string String16 {
            get {
                return ResourceManager.GetString("String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Организация не работает.
        /// </summary>
        public static string String17 {
            get {
                return ResourceManager.GetString("String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не могу найти адрес.
        /// </summary>
        public static string String18 {
            get {
                return ResourceManager.GetString("String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смена адреса.
        /// </summary>
        public static string String19 {
            get {
                return ResourceManager.GetString("String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тел. недоступен.
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Требуется доп. информация для забора груза.
        /// </summary>
        public static string String20 {
            get {
                return ResourceManager.GetString("String20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отказ от получения/ от заявки.
        /// </summary>
        public static string String21 {
            get {
                return ResourceManager.GetString("String21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перенос даты.
        /// </summary>
        public static string String22 {
            get {
                return ResourceManager.GetString("String22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Требуется пропуск/ограниченный доступ.
        /// </summary>
        public static string String23 {
            get {
                return ResourceManager.GetString("String23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет паспорта/копии.
        /// </summary>
        public static string String24 {
            get {
                return ResourceManager.GetString("String24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет купона.
        /// </summary>
        public static string String25 {
            get {
                return ResourceManager.GetString("String25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нужен чек.
        /// </summary>
        public static string String26 {
            get {
                return ResourceManager.GetString("String26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет доверенности от получателя.
        /// </summary>
        public static string String27 {
            get {
                return ResourceManager.GetString("String27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет доверенности от СДЭК.
        /// </summary>
        public static string String28 {
            get {
                return ResourceManager.GetString("String28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Требуются документы.
        /// </summary>
        public static string String29 {
            get {
                return ResourceManager.GetString("String29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не берут трубку.
        /// </summary>
        public static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Груз не вошел в авто.
        /// </summary>
        public static string String30 {
            get {
                return ResourceManager.GetString("String30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Требуется курьер на авто/газель.
        /// </summary>
        public static string String31 {
            get {
                return ResourceManager.GetString("String31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправитель требует расписаться в документах.
        /// </summary>
        public static string String32 {
            get {
                return ResourceManager.GetString("String32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очередь на выдачу груза.
        /// </summary>
        public static string String33 {
            get {
                return ResourceManager.GetString("String33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Я жду звонка от оператора.
        /// </summary>
        public static string String34 {
            get {
                return ResourceManager.GetString("String34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не успеваю.
        /// </summary>
        public static string String35 {
            get {
                return ResourceManager.GetString("String35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Самозабор.
        /// </summary>
        public static string String36 {
            get {
                return ResourceManager.GetString("String36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Постомат переполнен.
        /// </summary>
        public static string String37 {
            get {
                return ResourceManager.GetString("String37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Постомат не работает.
        /// </summary>
        public static string String38 {
            get {
                return ResourceManager.GetString("String38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Груз не влез в ячейку постомата.
        /// </summary>
        public static string String39 {
            get {
                return ResourceManager.GetString("String39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не успел.
        /// </summary>
        public static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отказ от получения.
        /// </summary>
        public static string String40 {
            get {
                return ResourceManager.GetString("String40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отказ от заявки.
        /// </summary>
        public static string String41 {
            get {
                return ResourceManager.GetString("String41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Требуется пропуск.
        /// </summary>
        public static string String42 {
            get {
                return ResourceManager.GetString("String42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Платный въезд.
        /// </summary>
        public static string String43 {
            get {
                return ResourceManager.GetString("String43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрытая территория.
        /// </summary>
        public static string String44 {
            get {
                return ResourceManager.GetString("String44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет документа удостоверяющего личность.
        /// </summary>
        public static string String45 {
            get {
                return ResourceManager.GetString("String45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смена города.
        /// </summary>
        public static string String46 {
            get {
                return ResourceManager.GetString("String46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес не существует.
        /// </summary>
        public static string String47 {
            get {
                return ResourceManager.GetString("String47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доставка в А/Я.
        /// </summary>
        public static string String48 {
            get {
                return ResourceManager.GetString("String48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Опасный груз.
        /// </summary>
        public static string String49 {
            get {
                return ResourceManager.GetString("String49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неисправность авто.
        /// </summary>
        public static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разрешено (только для типа заказа &quot;доставка&quot; и заказам до постамата).
        /// </summary>
        public static string String50 {
            get {
                return ResourceManager.GetString("String50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разрешено (Исключение - заказы до постамата).
        /// </summary>
        public static string String51 {
            get {
                return ResourceManager.GetString("String51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отказ с адреса.
        /// </summary>
        public static string String52 {
            get {
                return ResourceManager.GetString("String52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменение интервала по согласованию с клиентом.
        /// </summary>
        public static string String53 {
            get {
                return ResourceManager.GetString("String53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Постаматное приложение не работает.
        /// </summary>
        public static string String54 {
            get {
                return ResourceManager.GetString("String54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Груз не найден.
        /// </summary>
        public static string String55 {
            get {
                return ResourceManager.GetString("String55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Передача на ПВЗ.
        /// </summary>
        public static string String56 {
            get {
                return ResourceManager.GetString("String56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не могу доставить на ПВЗ.
        /// </summary>
        public static string String57 {
            get {
                return ResourceManager.GetString("String57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрещено, начисляется автоматически.
        /// </summary>
        public static string String58 {
            get {
                return ResourceManager.GetString("String58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрещено, начисляется автоматически.
        /// </summary>
        public static string String59 {
            get {
                return ResourceManager.GetString("String59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный адрес.
        /// </summary>
        public static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разрешено.
        /// </summary>
        public static string String60 {
            get {
                return ResourceManager.GetString("String60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрещено, начисляется автоматически.
        /// </summary>
        public static string String61 {
            get {
                return ResourceManager.GetString("String61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрещено, начисляется автоматически.
        /// </summary>
        public static string String62 {
            get {
                return ResourceManager.GetString("String62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрещено, начисляется автоматически.
        /// </summary>
        public static string String63 {
            get {
                return ResourceManager.GetString("String63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрещено, начисляется сотрудником СДЭК.
        /// </summary>
        public static string String64 {
            get {
                return ResourceManager.GetString("String64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрещено, начисляется автоматически.
        /// </summary>
        public static string String65 {
            get {
                return ResourceManager.GetString("String65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разрешено.
        /// </summary>
        public static string String66 {
            get {
                return ResourceManager.GetString("String66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разрешено (Исключение - заказы до постамата).
        /// </summary>
        public static string String67 {
            get {
                return ResourceManager.GetString("String67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрещено, начисляется сотрудником СДЭК.
        /// </summary>
        public static string String68 {
            get {
                return ResourceManager.GetString("String68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрещено, начисляется сотрудником СДЭК.
        /// </summary>
        public static string String69 {
            get {
                return ResourceManager.GetString("String69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отказ от заявки.
        /// </summary>
        public static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разрешено.
        /// </summary>
        public static string String70 {
            get {
                return ResourceManager.GetString("String70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступно только в ЛК и при оформлении через Call-центр (Запрещено для заказов до постамата).
        /// </summary>
        public static string String71 {
            get {
                return ResourceManager.GetString("String71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Только при оформлении через Call-центр
        ///(Запрещено для заказов до постамата).
        /// </summary>
        public static string String72 {
            get {
                return ResourceManager.GetString("String72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступно только в ЛК и при оформлении через Call-центр
        ///(Запрещено для заказов до постамата).
        /// </summary>
        public static string String73 {
            get {
                return ResourceManager.GetString("String73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разрешено (Исключение - заказы до постамата).
        /// </summary>
        public static string String74 {
            get {
                return ResourceManager.GetString("String74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрещено, начисляется автоматически в зависимости от условий договора.
        /// </summary>
        public static string String75 {
            get {
                return ResourceManager.GetString("String75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступно только в ЛК и при оформлении через Call-центр
        ///(Запрещено для заказов до постамата).
        /// </summary>
        public static string String76 {
            get {
                return ResourceManager.GetString("String76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступно только в ЛК и при оформлении через Call-центр
        ///(Запрещено для заказов до постамата).
        /// </summary>
        public static string String77 {
            get {
                return ResourceManager.GetString("String77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрещено, начисляется автоматически.
        /// </summary>
        public static string String78 {
            get {
                return ResourceManager.GetString("String78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разрешено (Исключение - заказы до постамата).
        /// </summary>
        public static string String79 {
            get {
                return ResourceManager.GetString("String79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не знают что отправлять.
        /// </summary>
        public static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разрешено (Исключение - заказы до постамата).
        /// </summary>
        public static string String80 {
            get {
                return ResourceManager.GetString("String80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрещено, начисляется автоматически.
        /// </summary>
        public static string String81 {
            get {
                return ResourceManager.GetString("String81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрещено, начисляется автоматически.
        /// </summary>
        public static string String82 {
            get {
                return ResourceManager.GetString("String82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрещено, начисляется автоматически.
        /// </summary>
        public static string String83 {
            get {
                return ResourceManager.GetString("String83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разрешено (Исключение - заказы до постамата).
        /// </summary>
        public static string String84 {
            get {
                return ResourceManager.GetString("String84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СТРАХОВАНИЕ.
        /// </summary>
        public static string String85 {
            get {
                return ResourceManager.GetString("String85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ДОСТАВКА В ВЫХОДНОЙ ДЕНЬ.
        /// </summary>
        public static string String86 {
            get {
                return ResourceManager.GetString("String86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ТЯЖЕЛЫЙ ГРУЗ.
        /// </summary>
        public static string String87 {
            get {
                return ResourceManager.GetString("String87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на НЕГАБАРИТНЫЙ ГРУЗ.
        /// </summary>
        public static string String88 {
            get {
                return ResourceManager.GetString("String88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОПАСНЫЙ ГРУЗ.
        /// </summary>
        public static string String89 {
            get {
                return ResourceManager.GetString("String89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Груз не готов.
        /// </summary>
        public static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОЖИДАНИЕ БОЛЕЕ 15 МИН. У ОТПРАВИТЕЛЯ.
        /// </summary>
        public static string String90 {
            get {
                return ResourceManager.GetString("String90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОЖИДАНИЕ БОЛЕЕ 15 МИН. У ПОЛУЧАТЕЛЯ.
        /// </summary>
        public static string String91 {
            get {
                return ResourceManager.GetString("String91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ХРАНЕНИЕ НА СКЛАДЕ.
        /// </summary>
        public static string String92 {
            get {
                return ResourceManager.GetString("String92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПРОЧЕЕ.
        /// </summary>
        public static string String93 {
            get {
                return ResourceManager.GetString("String93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на УДАЛЕННЫЙ РАЙОН.
        /// </summary>
        public static string String94 {
            get {
                return ResourceManager.GetString("String94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПОВТОРНАЯ ПОЕЗДКА.
        /// </summary>
        public static string String95 {
            get {
                return ResourceManager.GetString("String95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЗАБОР В ГОРОДЕ ОТПРАВИТЕЛЕ.
        /// </summary>
        public static string String96 {
            get {
                return ResourceManager.GetString("String96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ДОСТАВКА В ГОРОДЕ ПОЛУЧАТЕЛЕ.
        /// </summary>
        public static string String97 {
            get {
                return ResourceManager.GetString("String97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПЕНЯ.
        /// </summary>
        public static string String98 {
            get {
                return ResourceManager.GetString("String98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОБРЕШЕТКА ГРУЗА.
        /// </summary>
        public static string String99 {
            get {
                return ResourceManager.GetString("String99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Абонент недоступен.
        /// </summary>
        public static string SubscriberUnavailable {
            get {
                return ResourceManager.GetString("SubscriberUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Срочная доставка документов и грузов «из рук в руки» по России к определенному часу (доставка за 1-2 суток)..
        /// </summary>
        public static string SuperExpressDescription {
            get {
                return ResourceManager.GetString("SuperExpressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Супер-экспресс до 10.
        /// </summary>
        public static string SuperExpressTo10 {
            get {
                return ResourceManager.GetString("SuperExpressTo10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Супер-экспресс до 12.
        /// </summary>
        public static string SuperExpressTo12 {
            get {
                return ResourceManager.GetString("SuperExpressTo12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Супер-экспресс до 14.
        /// </summary>
        public static string SuperExpressTo14 {
            get {
                return ResourceManager.GetString("SuperExpressTo14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Супер-экспресс до 16.
        /// </summary>
        public static string SuperExpressTo16 {
            get {
                return ResourceManager.GetString("SuperExpressTo16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Супер-экспресс до 9.
        /// </summary>
        public static string SuperExpressTo9 {
            get {
                return ResourceManager.GetString("SuperExpressTo9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не задан тариф или список тарифов.
        /// </summary>
        public static string TariffOrTariffList {
            get {
                return ResourceManager.GetString("TariffOrTariffList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тайский бат.
        /// </summary>
        public static string THB {
            get {
                return ResourceManager.GetString("THB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Почтовый индекс города-получателя отсутствует в базе СДЭК.
        /// </summary>
        public static string ThePostalCodeOfTheRecipientCity {
            get {
                return ResourceManager.GetString("ThePostalCodeOfTheRecipientCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Почтовый индекс города-отправителя отсутствует в базе СДЭК.
        /// </summary>
        public static string ThePpostalCode {
            get {
                return ResourceManager.GetString("ThePpostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Абонент не берет трубку.
        /// </summary>
        public static string TheSubscriberDoesNotPickUpThePhone {
            get {
                return ResourceManager.GetString("TheSubscriberDoesNotPickUpThePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Турецкая лира.
        /// </summary>
        public static string TL {
            get {
                return ResourceManager.GetString("TL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Гривна.
        /// </summary>
        public static string UAH {
            get {
                return ResourceManager.GetString("UAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доллар США.
        /// </summary>
        public static string USD {
            get {
                return ResourceManager.GetString("USD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Узбекский сум.
        /// </summary>
        public static string UZS {
            get {
                return ResourceManager.GetString("UZS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0%.
        /// </summary>
        public static string VAT0 {
            get {
                return ResourceManager.GetString("VAT0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 10%.
        /// </summary>
        public static string VAT10 {
            get {
                return ResourceManager.GetString("VAT10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 20%.
        /// </summary>
        public static string VAT20 {
            get {
                return ResourceManager.GetString("VAT20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на БЕЗ НДС.
        /// </summary>
        public static string VATX {
            get {
                return ResourceManager.GetString("VATX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на склад-дверь.
        /// </summary>
        public static string WarehouseDoor {
            get {
                return ResourceManager.GetString("WarehouseDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправитель доставляет груз самостоятельно до склада, курьер доставляет получателю на указанный адрес..
        /// </summary>
        public static string WarehouseDoorDescription {
            get {
                return ResourceManager.GetString("WarehouseDoorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на склад-постамат.
        /// </summary>
        public static string WarehousePostomat {
            get {
                return ResourceManager.GetString("WarehousePostomat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправитель доставляет груз самостоятельно до склада, курьер доставляет в указанный постамат, получатель забирает груз самостоятельно из постамата.
        /// </summary>
        public static string WarehousePostomatDescription {
            get {
                return ResourceManager.GetString("WarehousePostomatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на склад-склад.
        /// </summary>
        public static string WarehouseWarehouse {
            get {
                return ResourceManager.GetString("WarehouseWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправитель доставляет груз самостоятельно до склада, получатель забирает груз самостоятельно в ПВЗ (самозабор)..
        /// </summary>
        public static string WarehouseWarehouseDescription {
            get {
                return ResourceManager.GetString("WarehouseWarehouseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При авторизации не задана дата планируемой отправки.
        /// </summary>
        public static string WhenAuthorizingError {
            get {
                return ResourceManager.GetString("WhenAuthorizingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный номер.
        /// </summary>
        public static string WrongNumber {
            get {
                return ResourceManager.GetString("WrongNumber", resourceCulture);
            }
        }
    }
}
