//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklad_v1_001.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sklad_v1_001.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ДОБАВИТЬ.
        /// </summary>
        public static string ADD {
            get {
                return ResourceManager.GetString("ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поставщик.
        /// </summary>
        public static string ADDDELIVERY {
            get {
                return ResourceManager.GetString("ADDDELIVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл инвойса.
        /// </summary>
        public static string AddFileInvoice {
            get {
                return ResourceManager.GetString("AddFileInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл оплаты.
        /// </summary>
        public static string AddFileRRN {
            get {
                return ResourceManager.GetString("AddFileRRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл ТТН.
        /// </summary>
        public static string AddFileTTN {
            get {
                return ResourceManager.GetString("AddFileTTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string ADDLIST {
            get {
                return ResourceManager.GetString("ADDLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый продукт.
        /// </summary>
        public static string ADDPRODUCT {
            get {
                return ResourceManager.GetString("ADDPRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адресс доставки.
        /// </summary>
        public static string Adress {
            get {
                return ResourceManager.GetString("Adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма оплаты.
        /// </summary>
        public static string AmountPayment {
            get {
                return ResourceManager.GetString("AmountPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Итого в RUS.
        /// </summary>
        public static string AmountRUS {
            get {
                return ResourceManager.GetString("AmountRUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Итого в USA.
        /// </summary>
        public static string AmountUSA {
            get {
                return ResourceManager.GetString("AmountUSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применить.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердить.
        /// </summary>
        public static string APPLYBUTTON {
            get {
                return ResourceManager.GetString("APPLYBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        public static string AsteriskTitle {
            get {
                return ResourceManager.GetString("AsteriskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предыдущая.
        /// </summary>
        public static string BACK {
            get {
                return ResourceManager.GetString("BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В начало.
        /// </summary>
        public static string BACKIN {
            get {
                return ResourceManager.GetString("BACKIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на неверный дифпазон.
        /// </summary>
        public static string BadRange {
            get {
                return ResourceManager.GetString("BadRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оплачено.
        /// </summary>
        public static string BalanceAmount {
            get {
                return ResourceManager.GetString("BalanceAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Штрих-код.
        /// </summary>
        public static string BarCodeID {
            get {
                return ResourceManager.GetString("BarCodeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория.
        /// </summary>
        public static string CATEGORY {
            get {
                return ResourceManager.GetString("CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;ВЫБРАТЬ&gt;.
        /// </summary>
        public static string Category0 {
            get {
                return ResourceManager.GetString("Category0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар.
        /// </summary>
        public static string Category1 {
            get {
                return ResourceManager.GetString("Category1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сопуствующий товар.
        /// </summary>
        public static string Category2 {
            get {
                return ResourceManager.GetString("Category2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подкатегория.
        /// </summary>
        public static string CATEGORYDETAILS {
            get {
                return ResourceManager.GetString("CATEGORYDETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;ВЫБРАТЬ&gt;.
        /// </summary>
        public static string CategoryDetails0 {
            get {
                return ResourceManager.GetString("CategoryDetails0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория.
        /// </summary>
        public static string CategoryDetails1 {
            get {
                return ResourceManager.GetString("CategoryDetails1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подкатегория.
        /// </summary>
        public static string CategoryDetails2 {
            get {
                return ResourceManager.GetString("CategoryDetails2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование категории.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория продукции.
        /// </summary>
        public static string CategoryTypeProduct {
            get {
                return ResourceManager.GetString("CategoryTypeProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена.
        /// </summary>
        public static string CenaProduct {
            get {
                return ResourceManager.GetString("CenaProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доставка.
        /// </summary>
        public static string CompanyDelivery {
            get {
                return ResourceManager.GetString("CompanyDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сегодня.
        /// </summary>
        public static string CurrentDay {
            get {
                return ResourceManager.GetString("CurrentDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За сегодня.
        /// </summary>
        public static string DateTimeDescription1 {
            get {
                return ResourceManager.GetString("DateTimeDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За неделю.
        /// </summary>
        public static string DateTimeDescription2 {
            get {
                return ResourceManager.GetString("DateTimeDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За месяц.
        /// </summary>
        public static string DateTimeDescription3 {
            get {
                return ResourceManager.GetString("DateTimeDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За периуд.
        /// </summary>
        public static string DateTimeDescription4 {
            get {
                return ResourceManager.GetString("DateTimeDescription4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все.
        /// </summary>
        public static string DateTimeDescriptionAll {
            get {
                return ResourceManager.GetString("DateTimeDescriptionAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на УДАЛИТЬ.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на удаление.
        /// </summary>
        public static string Deletion {
            get {
                return ResourceManager.GetString("Deletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цен. дост в RUS.
        /// </summary>
        public static string DelivaryAmountRUS {
            get {
                return ResourceManager.GetString("DelivaryAmountRUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цен. дост в USA.
        /// </summary>
        public static string DelivaryAmountUSA {
            get {
                return ResourceManager.GetString("DelivaryAmountUSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поставки.
        /// </summary>
        public static string Deliveries {
            get {
                return ResourceManager.GetString("Deliveries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Компания транспортировки.
        /// </summary>
        public static string DeliveriesCompany {
            get {
                return ResourceManager.GetString("DeliveriesCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес доставки.
        /// </summary>
        public static string DeliveryAdress {
            get {
                return ResourceManager.GetString("DeliveryAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Черновик.
        /// </summary>
        public static string DeliveryType1 {
            get {
                return ResourceManager.GetString("DeliveryType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправлен.
        /// </summary>
        public static string DeliveryType2 {
            get {
                return ResourceManager.GetString("DeliveryType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получено.
        /// </summary>
        public static string DeliveryType3 {
            get {
                return ResourceManager.GetString("DeliveryType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменен.
        /// </summary>
        public static string DeliveryType4 {
            get {
                return ResourceManager.GetString("DeliveryType4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание  продукта.
        /// </summary>
        public static string DescriptionProduct {
            get {
                return ResourceManager.GetString("DescriptionProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание.
        /// </summary>
        public static string Discription {
            get {
                return ResourceManager.GetString("Discription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Должность.
        /// </summary>
        public static string Dolwnost {
            get {
                return ResourceManager.GetString("Dolwnost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Детали.
        /// </summary>
        public static string EDITBUTTON {
            get {
                return ResourceManager.GetString("EDITBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на пустое поле.
        /// </summary>
        public static string EmptyField {
            get {
                return ResourceManager.GetString("EmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на пустой фильтр.
        /// </summary>
        public static string EmptyFilter {
            get {
                return ResourceManager.GetString("EmptyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите категорию.
        /// </summary>
        public static string ErrorCategory0 {
            get {
                return ResourceManager.GetString("ErrorCategory0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заполните обязательное поле.
        /// </summary>
        public static string ErrorEmptyField {
            get {
                return ResourceManager.GetString("ErrorEmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение поля ДО меньше значения поля ОТ.
        /// </summary>
        public static string ErrorFilterToSmallerFrom {
            get {
                return ResourceManager.GetString("ErrorFilterToSmallerFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание.
        /// </summary>
        public static string ExclamationTitle {
            get {
                return ResourceManager.GetString("ExclamationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        public static string Exite {
            get {
                return ResourceManager.GetString("Exite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Временной фильтр.
        /// </summary>
        public static string FilterTime {
            get {
                return ResourceManager.GetString("FilterTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтер.
        /// </summary>
        public static string FilterTitle {
            get {
                return ResourceManager.GetString("FilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть фильтер.
        /// </summary>
        public static string FliterClose {
            get {
                return ResourceManager.GetString("FliterClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на От куда идет.
        /// </summary>
        public static string FromWhere {
            get {
                return ResourceManager.GetString("FromWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string HandTitle {
            get {
                return ResourceManager.GetString("HandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на №.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        public static string InformationTitle {
            get {
                return ResourceManager.GetString("InformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на №-заказа.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на наимен. столбца.
        /// </summary>
        public static string LableText {
            get {
                return ResourceManager.GetString("LableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата модифик..
        /// </summary>
        public static string LastModifiadDateText {
            get {
                return ResourceManager.GetString("LastModifiadDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список компаний доставки.
        /// </summary>
        public static string ListDelivery {
            get {
                return ResourceManager.GetString("ListDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на К списку документов.
        /// </summary>
        public static string LISTDOCUMENT {
            get {
                return ResourceManager.GetString("LISTDOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список оплат.
        /// </summary>
        public static string ListPayment {
            get {
                return ResourceManager.GetString("ListPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список товаров.
        /// </summary>
        public static string ListProducts {
            get {
                return ResourceManager.GetString("ListProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список продаж.
        /// </summary>
        public static string ListSaleDocument {
            get {
                return ResourceManager.GetString("ListSaleDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список поставок.
        /// </summary>
        public static string ListSupplyDocument {
            get {
                return ResourceManager.GetString("ListSupplyDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расположение.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Менеджер по продажам.
        /// </summary>
        public static string ManagerCompany {
            get {
                return ResourceManager.GetString("ManagerCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Менеджер компании.
        /// </summary>
        public static string ManagerDelivery {
            get {
                return ResourceManager.GetString("ManagerDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить.
        /// </summary>
        public static string MessageAbort {
            get {
                return ResourceManager.GetString("MessageAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string MessageCancel {
            get {
                return ResourceManager.GetString("MessageCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пропустить.
        /// </summary>
        public static string MessageIgnore {
            get {
                return ResourceManager.GetString("MessageIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        public static string MessageNo {
            get {
                return ResourceManager.GetString("MessageNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОК.
        /// </summary>
        public static string MessageOK {
            get {
                return ResourceManager.GetString("MessageOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторить.
        /// </summary>
        public static string MessageRetry {
            get {
                return ResourceManager.GetString("MessageRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        public static string MessageYes {
            get {
                return ResourceManager.GetString("MessageYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модель.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПРИЧИНА.
        /// </summary>
        public static string MOTIVE {
            get {
                return ResourceManager.GetString("MOTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование категории.
        /// </summary>
        public static string NameCategory {
            get {
                return ResourceManager.GetString("NameCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование компании.
        /// </summary>
        public static string NameDelivery {
            get {
                return ResourceManager.GetString("NameDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ФИО.
        /// </summary>
        public static string NameLast {
            get {
                return ResourceManager.GetString("NameLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование товара.
        /// </summary>
        public static string NameProduct {
            get {
                return ResourceManager.GetString("NameProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование под категории.
        /// </summary>
        public static string NameTypeCategory {
            get {
                return ResourceManager.GetString("NameTypeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ТОВАР.
        /// </summary>
        public static string NEWPRODUCT {
            get {
                return ResourceManager.GetString("NEWPRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новая продажа.
        /// </summary>
        public static string NewSaleDocument {
            get {
                return ResourceManager.GetString("NewSaleDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новая поставка.
        /// </summary>
        public static string NewSupplyDocument {
            get {
                return ResourceManager.GetString("NewSupplyDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Следующая.
        /// </summary>
        public static string NEXT {
            get {
                return ResourceManager.GetString("NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В конец.
        /// </summary>
        public static string NEXTEXIT {
            get {
                return ResourceManager.GetString("NEXTEXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ФИО менеджер.
        /// </summary>
        public static string NmaeManager {
            get {
                return ResourceManager.GetString("NmaeManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на №-документа.
        /// </summary>
        public static string NumberDocument {
            get {
                return ResourceManager.GetString("NumberDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на №-телефона.
        /// </summary>
        public static string NumberPhone {
            get {
                return ResourceManager.GetString("NumberPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на №-тел. гол.офисса.
        /// </summary>
        public static string NumberPhoneDelivery {
            get {
                return ResourceManager.GetString("NumberPhoneDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер Сотрудника.
        /// </summary>
        public static string NumberSotrudnika {
            get {
                return ResourceManager.GetString("NumberSotrudnika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на из.
        /// </summary>
        public static string OF {
            get {
                return ResourceManager.GetString("OF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип оплаты.
        /// </summary>
        public static string OperationType {
            get {
                return ResourceManager.GetString("OperationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наличные.
        /// </summary>
        public static string OperationType1 {
            get {
                return ResourceManager.GetString("OperationType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Банковская карта.
        /// </summary>
        public static string OperationType2 {
            get {
                return ResourceManager.GetString("OperationType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обмен.
        /// </summary>
        public static string OperationType3 {
            get {
                return ResourceManager.GetString("OperationType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Иным способом оплаты.
        /// </summary>
        public static string OperationType4 {
            get {
                return ResourceManager.GetString("OperationType4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчество.
        /// </summary>
        public static string Otchestvo {
            get {
                return ResourceManager.GetString("Otchestvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отдел.
        /// </summary>
        public static string Otdel {
            get {
                return ResourceManager.GetString("Otdel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Упаковка.
        /// </summary>
        public static string Package {
            get {
                return ResourceManager.GetString("Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Упаковка есть?.
        /// </summary>
        public static string PackageYEStoNOT {
            get {
                return ResourceManager.GetString("PackageYEStoNOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Страница.
        /// </summary>
        public static string PAGE {
            get {
                return ResourceManager.GetString("PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на из.
        /// </summary>
        public static string PageIn {
            get {
                return ResourceManager.GetString("PageIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оплачено.
        /// </summary>
        public static string Payment1 {
            get {
                return ResourceManager.GetString("Payment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не оплачено.
        /// </summary>
        public static string Payment2 {
            get {
                return ResourceManager.GetString("Payment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Денежный перевод.
        /// </summary>
        public static string Payment3 {
            get {
                return ResourceManager.GetString("Payment3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чек оплаты.
        /// </summary>
        public static string PaymentReceipt {
            get {
                return ResourceManager.GetString("PaymentReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип оплаты.
        /// </summary>
        public static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус оплаты.
        /// </summary>
        public static string PaymentTypeStatus {
            get {
                return ResourceManager.GetString("PaymentTypeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фото.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Должность.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Детали продукта.
        /// </summary>
        public static string ProductItemScreenTitle {
            get {
                return ResourceManager.GetString("ProductItemScreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продукты.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Детали продукта.
        /// </summary>
        public static string ProductsEdit {
            get {
                return ResourceManager.GetString("ProductsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория.
        /// </summary>
        public static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить данную запись?.
        /// </summary>
        public static string QuestionDelete {
            get {
                return ResourceManager.GetString("QuestionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердите действие.
        /// </summary>
        public static string QuestionTitle {
            get {
                return ResourceManager.GetString("QuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остаток.
        /// </summary>
        public static string RemainsAmount {
            get {
                return ResourceManager.GetString("RemainsAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сбросить фильтер.
        /// </summary>
        public static string ResetFilter {
            get {
                return ResourceManager.GetString("ResetFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Роль.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на №-транзакции.
        /// </summary>
        public static string RRN {
            get {
                return ResourceManager.GetString("RRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продажи.
        /// </summary>
        public static string SaleDocument {
            get {
                return ResourceManager.GetString("SaleDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить и выйти.
        /// </summary>
        public static string SAVECLOCE {
            get {
                return ResourceManager.GetString("SAVECLOCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string SAVELIST {
            get {
                return ResourceManager.GetString("SAVELIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № штрих-кода.
        /// </summary>
        public static string SchtrxCode {
            get {
                return ResourceManager.GetString("SchtrxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Штрих-код.
        /// </summary>
        public static string ShtrixCode {
            get {
                return ResourceManager.GetString("ShtrixCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размеры продукта.
        /// </summary>
        public static string SizeProduct {
            get {
                return ResourceManager.GetString("SizeProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string StopTitle {
            get {
                return ResourceManager.GetString("StopTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стоимость.
        /// </summary>
        public static string SummaSumm {
            get {
                return ResourceManager.GetString("SummaSumm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Черновик.
        /// </summary>
        public static string SupplyDocument1 {
            get {
                return ResourceManager.GetString("SupplyDocument1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получен.
        /// </summary>
        public static string SupplyDocument2 {
            get {
                return ResourceManager.GetString("SupplyDocument2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ в обработке.
        /// </summary>
        public static string SupplyDocument3 {
            get {
                return ResourceManager.GetString("SupplyDocument3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В пути.
        /// </summary>
        public static string SupplyDocument4 {
            get {
                return ResourceManager.GetString("SupplyDocument4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Документ поставки.
        /// </summary>
        public static string SupplyDocumentHeader {
            get {
                return ResourceManager.GetString("SupplyDocumentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Суммы.
        /// </summary>
        public static string SupplyDocumentHeaderSummary {
            get {
                return ResourceManager.GetString("SupplyDocumentHeaderSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поставки.
        /// </summary>
        public static string SupplyTitly {
            get {
                return ResourceManager.GetString("SupplyTitly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена закупки в RUB.
        /// </summary>
        public static string TagPriceRus {
            get {
                return ResourceManager.GetString("TagPriceRus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена закупки в USA.
        /// </summary>
        public static string TagPriceUSA {
            get {
                return ResourceManager.GetString("TagPriceUSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Временной фильтр.
        /// </summary>
        public static string TimeFilterMessage1 {
            get {
                return ResourceManager.GetString("TimeFilterMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Диапазон дат.
        /// </summary>
        public static string TitleFromToDateFilter {
            get {
                return ResourceManager.GetString("TitleFromToDateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма заказа.
        /// </summary>
        public static string TotalSumma {
            get {
                return ResourceManager.GetString("TotalSumma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер отслеживания.
        /// </summary>
        public static string TrackingNumber {
            get {
                return ResourceManager.GetString("TrackingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перемещение.
        /// </summary>
        public static string TransferDocument {
            get {
                return ResourceManager.GetString("TransferDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ТТН.
        /// </summary>
        public static string TTN {
            get {
                return ResourceManager.GetString("TTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип категории.
        /// </summary>
        public static string TypeCategory {
            get {
                return ResourceManager.GetString("TypeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория .
        /// </summary>
        public static string TypeProduct {
            get {
                return ResourceManager.GetString("TypeProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип доставки.
        /// </summary>
        public static string TypeВelivery {
            get {
                return ResourceManager.GetString("TypeВelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string UndefindField {
            get {
                return ResourceManager.GetString("UndefindField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сотрудник.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Витрина.
        /// </summary>
        public static string Vitrina {
            get {
                return ResourceManager.GetString("Vitrina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ветрина не выбрана.
        /// </summary>
        public static string Vitrina0 {
            get {
                return ResourceManager.GetString("Vitrina0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Витрина 1.
        /// </summary>
        public static string Vitrina1 {
            get {
                return ResourceManager.GetString("Vitrina1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Витрина 10.
        /// </summary>
        public static string Vitrina10 {
            get {
                return ResourceManager.GetString("Vitrina10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Витрина 2.
        /// </summary>
        public static string Vitrina2 {
            get {
                return ResourceManager.GetString("Vitrina2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Витрина 3.
        /// </summary>
        public static string Vitrina3 {
            get {
                return ResourceManager.GetString("Vitrina3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Витрина 4.
        /// </summary>
        public static string Vitrina4 {
            get {
                return ResourceManager.GetString("Vitrina4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Витрина 5.
        /// </summary>
        public static string Vitrina5 {
            get {
                return ResourceManager.GetString("Vitrina5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Витрина 6.
        /// </summary>
        public static string Vitrina6 {
            get {
                return ResourceManager.GetString("Vitrina6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Витрина 7.
        /// </summary>
        public static string Vitrina7 {
            get {
                return ResourceManager.GetString("Vitrina7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Витрина 8.
        /// </summary>
        public static string Vitrina8 {
            get {
                return ResourceManager.GetString("Vitrina8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Витрина 9.
        /// </summary>
        public static string Vitrina9 {
            get {
                return ResourceManager.GetString("Vitrina9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите хотя бы одно значение фильтра.
        /// </summary>
        public static string WarningNotChoosenFilter {
            get {
                return ResourceManager.GetString("WarningNotChoosenFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание.
        /// </summary>
        public static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Когда придет.
        /// </summary>
        public static string WhenItComes {
            get {
                return ResourceManager.GetString("WhenItComes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Когда заказали.
        /// </summary>
        public static string WhenOrdered {
            get {
                return ResourceManager.GetString("WhenOrdered", resourceCulture);
            }
        }
    }
}
